name: purse_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  animate_do: ^3.3.4
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.2.1
  bloc: ^8.1.2
  currency_picker: ^2.0.21
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fpdart: ^0.6.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_fonts: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  iconly: ^1.0.1
  # image_cropper: ^8.0.2
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_phone_number_field: ^0.2.1
  logger: ^1.4.0
  mime: ^2.0.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  pull_to_refresh: ^2.0.0
  responsive_sizer: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  top_snackbar_flutter: ^3.0.0+1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/translations/
